global:
  scrape_interval: 5s

scrape_configs:
  - job_name: envoy
    metrics_path: /stats/prometheus
    static_configs:
      - targets: ["envoy:9901"]

  - job_name: ratelimiter
    static_configs:
      - targets: ["ratelimiter:8000"]

  - job_name: echo
    static_configs:
      - targets: ["echo-grpc:9100"]

  - job_name: users
    static_configs:
      - targets: ["users-api:9101"]